[package]
name = "DirSearch"
version = "0.1.0"
edition = "2021"

[dependencies]
lopdf = { version = "0.34.0", features = ["pom", "pom_parser"] }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
lmdb = "0.8.0"
rust-stemmers = "=1.2.0"
anyhow = "1.0.93"